export const ADD_POSTCODE = 'ADD_POSTCODE';
export const ADD_RESTAURANT_DATA = 'ADD_RESTAURANT_DATA';
export const ADD_CURRENT_USER = 'ADD_CURRENT_USER';
export const ADD_SAVED_RESTAURANT_DATA = 'ADD_SAVED_RESTAURANT_DATA'; 
